### ISSUE TITLE
Issuer DIDComm Flow

### ISSUE THREAD

**Issue by rolsonquadras** [trustbloc/edge-sandbox#358]
- [x] Page with 'Connect Wallet' button https://github.com/trustbloc/edge-sandbox/issues/359
- [x] Fetch the DIDComm invitation from the adapter https://github.com/trustbloc/edge-sandbox/issues/360
- [x] Pass the DIDComm invitation in CHAPI to the wallet https://github.com/trustbloc/edge-sandbox/issues/361
- [x] Process the CHAPI response from the wallet https://github.com/trustbloc/edge-sandbox/issues/362
