### ISSUE TITLE
didcomm demo: rp adapter

### ISSUE THREAD

**Issue by llorllale** [trustbloc/edge-sandbox#382]
- [x] deploy rp adapter components #397 
- [x] rp.example.com
  - [x] startup configuration for oauth2 parameters #399
  - [x] "Get Credential from Wallet" button that redirects user to the rp adapter #399
  - [x] add oauth2 callback endpoint #404
  - [x] ~~pretty ui~~ using existing `vp.html`
